name: gTest
on:
  push:
    branches: [ main, starter, solution ]
  pull_request:
    branches: [ main, starter, solution ]
permissions:
  contents: write
jobs:
  install_gTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make script executable
      run:  git update-index --chmod=+x ./.github/scripts/install-googletest.sh
    - name: Run Install script
      run:  ./install-googletest.sh
    # - name: Clone GTest
    #   run:  git clone https://github.com/google/googletest.git
    # - name: Install gtest manually
    #   working-directory: ./googletest
    #   run:  sudo apt install python3-pip &&
    #         cmake . &&
    #         make &&
    #         sudo make install