name: gTest
on:
  push:
    branches: [ main, starter, solution ]
  pull_request:
    branches: [ main, starter, solution ]
permissions:
  contents: write
jobs:
  install_gTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Install script
      run:  ./install-googletest.sh